name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3
      - run: pip install poetry
      - run: poetry install
      - run: poetry run coverage run --source=dude -m dude
      - run: poetry run coverage xml
      - uses: codecov/codecov-action@v2.0.2
      - run: poetry build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
